#!/usr/bin/env python3
"""`osqar gsn` — GSN (Goal Structuring Notation) safety case support.

Reads ``.. safety-case::`` needs from a sphinx-needs ``needs.json`` export
and generates gsn2x-compatible YAML for PlantUML/TikZ/Graphviz rendering.

Requires ``gsn2x`` (pip install gsn2x) for rendering. When gsn2x is not
available, generation is skipped with a warning.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from tools.traceability_check import _load_needs, _collect_trace_links


SAFETY_CASE_PREFIX = "SC_"


def _extract_safety_cases(needs: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Filter needs to only safety-case types."""
    return [n for n in needs if str(n.get("id", "")).startswith(SAFETY_CASE_PREFIX)]


def _need_title(need: dict[str, Any]) -> str:
    return str(need.get("title", need.get("content", need.get("id", "")))).strip()


def _to_gsn2x_yaml(
    safety_cases: list[dict[str, Any]],
    needs_by_id: dict[str, dict[str, Any]],
) -> str:
    """Generate gsn2x YAML spec from safety-case needs.

    gsn2x format (simplified):
    ```yaml
    goal: "System is safe"
    id: G1
    strategies:
      - id: S1
        description: "Argument by testing"
        solutions:
          - id: Sn1
            description: "Test results"
            evidence: [REF1, REF2]
    ```
    """
    lines: list[str] = ["# Auto-generated by OSQAr — gsn2x safety case specification", ""]

    for sc in safety_cases:
        sc_id = str(sc.get("id", ""))
        goal_text = _need_title(sc)
        strategy_text = str(sc.get("strategy", "")).strip()
        context_text = str(sc.get("context", "")).strip()
        assumption_text = str(sc.get("assumption", "")).strip()

        lines.append(f"goal: \"{goal_text}\"")
        lines.append(f"id: {sc_id}")

        if context_text:
            lines.append(f"context: \"{context_text}\"")
        if assumption_text:
            lines.append(f"assumption: \"{assumption_text}\"")

        # Find linked verification/test evidence via traceability links
        linked = _collect_trace_links(sc)
        evidence_ids = sorted(
            lid for lid in linked
            if lid.startswith(("VER_", "TEST_")) and lid in needs_by_id
        )
        arch_ids = sorted(
            lid for lid in linked
            if lid.startswith("ARCH_") and lid in needs_by_id
        )

        if strategy_text or evidence_ids or arch_ids:
            lines.append("strategies:")
            strat_id = f"{sc_id}_ST"

            if strategy_text:
                strat_line = f"  - id: {strat_id}"
                lines.append(strat_line)
                lines.append(f'    description: "{strategy_text}"')
            else:
                lines.append(f"  - id: {strat_id}")

            # Solutions from evidence
            if evidence_ids:
                lines.append("    solutions:")
                for eid in evidence_ids:
                    sn_id = f"{strat_id}_SN_{eid}"
                    etitle = _need_title(needs_by_id.get(eid, {}))
                    lines.append(f"      - id: {sn_id}")
                    lines.append(f'        description: "{etitle}"')
                    lines.append(f"        evidence: [{eid}]")

            # Architecture as context/assumption nodes
            if arch_ids and not evidence_ids:
                lines.append("    solutions:")
                for aid in arch_ids:
                    sn_id = f"{strat_id}_SN_{aid}"
                    atitle = _need_title(needs_by_id.get(aid, {}))
                    lines.append(f"      - id: {sn_id}")
                    lines.append(f'        description: "{atitle}"')
                    lines.append(f"        evidence: [{aid}]")

        lines.append("")

    return "\n".join(lines)


def cmd_gsn_generate(args: argparse.Namespace) -> int:
    needs_json = Path(args.needs_json).expanduser().resolve()
    if not needs_json.is_file():
        print(f"ERROR: needs.json not found: {needs_json}", file=sys.stderr)
        return 2

    try:
        needs = _load_needs(needs_json)
    except Exception as exc:
        print(f"ERROR: Failed to read {needs_json}: {exc}", file=sys.stderr)
        return 2

    scs = _extract_safety_cases(needs)
    if not scs:
        print("No safety-case needs found (prefix: SC_). Nothing to generate.")
        return 0

    needs_by_id: dict[str, dict[str, Any]] = {}
    for n in needs:
        nid = str(n.get("id", ""))
        if nid:
            needs_by_id[nid] = n

    yaml_spec = _to_gsn2x_yaml(scs, needs_by_id)

    output = Path(args.output).expanduser().resolve() if getattr(args, "output", None) else Path("gsn_safety_case.yaml")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(yaml_spec, encoding="utf-8")

    print(f"GSN specification written: {output}")
    print(f"  {len(scs)} safety-case needs processed")

    # Try rendering with gsn2x if requested
    if bool(getattr(args, "render", False)):
        try:
            import subprocess
            result = subprocess.run(
                [sys.executable, "-m", "gsn2x", str(output), "--backend", "plantuml"],
                capture_output=True, text=True,
            )
            if result.returncode == 0:
                print(f"  GSN diagram rendered (PlantUML)")
                if result.stdout.strip():
                    print(result.stdout.strip())
            else:
                print(f"  WARNING: gsn2x render failed: {result.stderr.strip()}")
        except Exception:
            print("  WARNING: gsn2x not available. Install with: pip install gsn2x")
            print("  The YAML spec can be rendered manually: gsn2x gsn_safety_case.yaml --backend plantuml")

    return 0


def register(sub: argparse._SubParsersAction) -> None:
    p_gsn = sub.add_parser(
        "gsn",
        help="GSN safety case support (generate gsn2x specifications from safety-case needs)",
    )
    gsn_sub = p_gsn.add_subparsers(dest="gsn_cmd", required=True)

    p_gen = gsn_sub.add_parser("generate", help="Generate gsn2x YAML from needs.json")
    p_gen.add_argument("needs_json", type=Path, help="Path to needs.json")
    p_gen.add_argument("--output", default=None, help="Output YAML path (default: gsn_safety_case.yaml)")
    p_gen.add_argument("--render", action="store_true", help="Also render via gsn2x (requires: pip install gsn2x)")
    p_gen.set_defaults(func=cmd_gsn_generate)
